Map well-known types for method signatures too
tenx-tech/prost pull request #1
Opened 2018-12-28 16:09 UTC by dingxiangfei2009

We did not map well-known types in method signatures over. This PR intends to fix that, temporarily.

Note that the upstream has fixed this issue, though the APIs are different.

2018-12-28 16:10 UTC, dingxiangfei2009 commented on prost-build/src/code_generator.rs
> +                let input_type = if let Some(ty) = self.known_type(&input_proto_type) {
This is the relevant changes. The other lines of changes in this hunk is due to unintentionally triggered `rustfmt`.

2018-12-31 06:06 UTC, TylerRichie requested changes
I would prefer we find a way to stop using this fork and use upstream instead of further diverging the fork from upstream. These forks are expensive, and prost in particular is used all over our code base.

2019-01-02 04:28 UTC, trha submitted a review, later dismissed

2019-01-10 06:25 UTC, TylerRichie commented
Can we close this PR, and even better: can we archive this fork? Everything in this repo is public, including all of the comments.

2019-01-21 08:00 UTC, ebkalderon reviewed
Is this PR still being worked on?

2019-01-23 10:54 UTC, dingxiangfei2009 commented
Closing for thinking about other strategies

2019-01-23 10:54 UTC, closed without merging